### ISSUE TITLE
How to process `xpacket` in `toVdom`

### ISSUE THREAD

**Issue by SantosGuillamot** [luisherranz/block-hydration-experiments#117]
We've found a couple of sites that have `xpacket` sections: [talsunovads.lv](https://href.li/?https://talsunovads.lv/) and [hlz.de](https://href.li/?http://hlz.de/).

Checking the [nodeType](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType), it seems they are considered `nodeType` 7. As we are not handling that use case, it returns an error: `TypeError: Cannot read properties of undefined (reading 'length')`.

We have to decide what to do with these nodes. Should we do the same as with [CDATA nodes](https://github.com/WordPress/block-hydration-experiments/issues/109)? It seems a similar case, as they are included inside the SVGs.

**Comment by DAreRodz** [comment]
> Should we do the same as with [CDATA nodes](https://github.com/WordPress/block-hydration-experiments/issues/109)? It seems a similar case, as they are included inside the SVGs.

It's a similar case indeed, but I think we should remove them in this case like we are doing with comments.

To be honest, I don't fully understand how browsers handle [Processing Instruction](https://developer.mozilla.org/en-US/docs/Web/API/ProcessingInstruction) nodes once they're instantiated. And the only thing I've found regarding `xpacket` instructions is that they work as opening and closing tags of [XMP](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform) metadata sections in media files.
