### ISSUE TITLE
Merge inherited `wp-context` properties from a parent instance

### ISSUE THREAD

**Issue by DAreRodz** [luisherranz/block-hydration-experiments#137]
If a `wp-context` directive is nested under another `wp-context` instance, the properties defined in the parent context should also be available inside the nested context.

```jsx
const WpContextExample = () => {
  const contextA = { a: 'foo' };
  const contextB = { b: 'bar' };

  return (
    <div wp-context={JSON.stringify(contextA)}>
      <div wp-context={JSON.stringify(contextB)}>
        {/* `context.a` and `context.b` should be accessible here */}
      </div>
    <div>
  );
}
``` 

Right now, only `context.b` is accessible in that scope because `contextB` replaces `contextA` entirely.

We need to implement `wp-context` so that all the previous properties that don't collide are preserved, even when they are nested.

In addition, we need to agree on how [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) objects would be merged. We can either append the elements or replace them according to their index.

**Comment by luisherranz** [comment]
Alpine is doing a replace: https://stackblitz.com/edit/web-platform-ktyzy9?file=index.html

If I recall correctly, at Frontity we did a merge so people could add options (processors and the like) using arrays in their `frontity.settings.js` files. But we later realized that it was impossible to remove items from the state definition, having to resort to code, so we moved all the arrays to objects.

We could follow Alpine's lead. @darerodz what do you think?

**Comment by DAreRodz** [comment]
Yup, that makes sense. We could implement that behavior.

**Comment by luisherranz** [comment]
@ockham is also using [replace in the SSR](https://github.com/WordPress/block-hydration-experiments/pull/133/files#diff-d5038f0e923a4b370eb61c523adc0baabd2c3187dfe7755b538b7e693e5e6649R62).
