### ISSUE TITLE
Decide the name of the npm package, like `@wordpress/interactivity`.

### ISSUE THREAD

**Issue by michalczaplinski** [luisherranz/block-hydration-experiments#146]
We should figure out if the npm package can simply be called `@wordpress/interactivity`.

**Comment by luisherranz** [comment]
For now, it seems like the package name is going to be `@wordpress/interactivity`. 

Please, feel free to open a new discussion in the [Interactivity API category](https://github.com/WordPress/gutenberg/discussions/categories/interactivity-api) if you think this should be discussed further.
