### ISSUE TITLE
SSR: Audit usage of `wp_process_directives`

### ISSUE THREAD

**Issue by ockham** [luisherranz/block-hydration-experiments#148]
@DAreRodz shared the following feedback with me in Slack:

> I have a couple of questions regarding directives evaluation and `wp-context`:
>
> I see that directives run inside `wp_process_directives()`, a callback added to the `render_block` hook—dispatched every time a block _has rendered_—, and uses `WP_HTML_Tag_Processor` to iterate over the HTML content, find the directives, and execute them.
>
> The questions are:
> 1. Isn’t that callback running several times for the same HTML?. E.g., if you have a block `A` and a block `B` inside `A`, both blocks will dispatch `render_block` when rendered. Won’t `B`'s directives run twice, one when `render_block` is dispatched for `B` and a second one for `A` (that would include `B` in its `$block_content`)?
> 2. `WP_Directive_Context` is instantiated for each `render_block` execution. Doesn’t it create a different context stack for each block? I guess it works in the end because we run directives inside inner blocks again (as mentioned in question 1.)?

**Comment by ockham** [comment]
I'm thinking to add a unit test for `wp_process_directives` (based on #144) that covers the inner blocks scenario, and to adjust `wp_process_directives` and/or plug into a different filter (other than `render_block`), if needed.

**Comment by luisherranz** [comment]
I'm going to close this issue as part of the migration to the Gutenberg repository.

This task was added to the Roadmap and we'll reopen an issue/discussion once it's time to start working on this again.
