### ISSUE TITLE
Merge new SSR context on client-side navigation

### ISSUE THREAD

**Issue by DAreRodz** [luisherranz/block-hydration-experiments#155]
Currently, an element's context (i.e., `wp-context`) is initialized once (during hydration). However, when client-side navigation happens, it could contain a newly defined context for the new HTML that should not be ignored.

We must read and merge the new context into the current one, keeping the existing props.

**Comment by luisherranz** [comment]
Also relevant here: https://github.com/WordPress/block-hydration-experiments/issues/154#issuecomment-1437288627

**Comment by luisherranz** [comment]
I made a preliminary version of this [in the WooCommerce repo](https://github.com/woocommerce/woocommerce-blocks/pull/10006/commits/4d579a033d9a22bea94931a7c3385867df6ebb56) because they need it.
