### ISSUE TITLE
Add `data-wp-key` attribute

### ISSUE THREAD

**Issue by luisherranz** [luisherranz/block-hydration-experiments#180]
Sometimes we are going to need a `key` prop in some tags to improve the client-side navigation diffing, but `key` is not a valid HTML attribute. I suggest adding `data-wp-key` and then copying its value to `props.key` during the creation of the virtual nodes.

**Comment by SantosGuillamot** [comment]
For reference, we needed a `key` prop to improve the diffing of the images in the [Movies demo](https://github.com/WordPress/wp-movies-demo/). We ended up [using the HTML Tag Processor to add a key attribute to all the images](https://github.com/WordPress/wp-movies-demo/blob/main/wpmovies.php#L129-L135), but it would be great to have that `data-wp-key` attribute.
