### ISSUE TITLE
Using useRef/wp-ref to get a reference to the DOM element

### ISSUE THREAD

**Issue by gaambo** [luisherranz/block-hydration-experiments#218]
Using useRef is necessary in some preact frontends if using an external vanilla-/jquery-library (eg for a slider, accordeon,...). Preact has got the `useRef`hook and alpinejs the `x-ref` attribute. 
The proposal blog article says that a ref to the dom element is passed on actions - but with alpinejs `x-ref` one can get a reference even on init/directly after init.
Will this also work with the syntax proposed here? 
That will be great to reuse non-(p)react libraries in the frontend and will make the switch for existing blocks way easier. 

I see #116 and #191 talking about refs, but I think both issues are in regards to the runtime of this framework, not to the calling code.

**Comment by luisherranz** [comment]
Sure. All directives and all actions/effects have access to the `ref` 🙂 

Have you seen any cases where that is not happening?

- Be aware that there's [a related bug](https://github.com/WordPress/block-interactivity-experiments/issues/191) but we intend to fix it this week. 
- Directives get it right now through `element.ref`, but maybe it should be just `ref`.

**Comment by luisherranz** [comment]
To save the reference for future use in either `state` or `context`, we are using this pattern:

```html
<div data-wp-init="effects.myPlugin.storeRef">...</div>
```

```js
store({
  effects: {
    myPlugin: {
      storeRef: ({ state, ref }) => {
        state.myPlugin.refToAnElement = ref;
      },
    },
  },
});
```

You can see that in action in [this experiment](https://github.com/WordPress/gutenberg/pull/44509/files#diff-ac3ab677b419ffc1a9537b403c75d082df4ce82942495c2fd7b880e83844002bR19-R21), although take into account that the syntax is a bit old.

I guess we could introduce a `data-wp-store-ref="state.myPlugin.refToAnElement` directive, but we prefer to wait until we see real use cases before we introduce higher-level directives.

**Comment by gaambo** [comment]
No bug found, just wanted to ask this question / drop a feature request and wasn't sure whether to open an issue or a discussion 😅
Calling an effect on init and storing the ref there into context/state looks good. Thanks for the explanation/documentation.
I agree that waiting for real uses cases before adding new directives is good step.

**Comment by luisherranz** [comment]
Thanks Fabian. Keep questions/suggestions coming! 🙂
