### ISSUE TITLE
Rename `data-wp-island` to `data-wp-interactive`

### ISSUE THREAD

**Issue by luisherranz** [luisherranz/block-hydration-experiments#238]
We inherited the name from the JavaScript ecosystem, but it's true that there's no context in WordPress to understand what is an island. So maybe we should rename it to `data-wp-interactive`. What do you think?

_Changed suggested by @carolinan [here](https://github.com/WordPress/gutenberg/pull/50373#pullrequestreview-1443037163)._

**Comment by SantosGuillamot** [comment]
It makes sense to me 🙂 I can imagine many users getting confused about what an island is, and they don't really need to know unless they are really interested.  `data-wp-interactive` seems clearer in that regard.

**Comment by luisherranz** [comment]
Ok, let's make this change then 🙂
