### ISSUE TITLE
Preact fails to reconcile scripts correctly when doing client-side navigation.

### ISSUE THREAD

**Issue by michalczaplinski** [luisherranz/block-hydration-experiments#242]
Originally reported in https://github.com/WordPress/wp-movies-demo/pull/52#issuecomment-1632897796

When client-side navigations are enabled, and the user navigates between two pages that load different scripts, Preact fails to reconcile the tree in the expected way.

Consider this situation:

#### page 1

```
<body>
  <script src="A.js">
  <script src="B.js">
  <script src="C.js">
</body>

```

#### page 2

```
<body>
  <script src="A.js">
  <script src="D.js">
  <script src="E.js">
  <script src="C.js">
</body>
```

In this case, Preact doesn't know that the `<script src="C.js">` is the same node and will re-render it which causes the `C.js` script to be downloaded again on the new page.

Reproduction on [StackBlitz](https://stackblitz.com/edit/demo-filters-multiple-queries-r3uekh?file=post.html)

**Comment by luisherranz** [comment]
Why are we letting Preact handle script insertion in this case? Is it not the purpose of the `fetchScriptOrStyle` logic to do so in a controlled manner?

**Comment by michalczaplinski** [comment]
> Why are we letting Preact handle script insertion in this case?

I don't think we are intentionally letting Preact handle this case. It's just that we didn't handle this behavior correctly before. Do you have a some specific idea on how to handle it?

I think that if a script has already been loaded and is in the [cache](https://github.com/WordPress/block-interactivity-experiments/blob/02b623b3a1a7523b9a80c6705d87e7450f8247cd/src/runtime/router.js#L12-L13), we should remove any `<script>` tags with a matching `src`. Just trying to validate the idea here, but this seems to work when I'm doing a quick test:

```diff
diff --git a/src/runtime/hooks.js b/src/runtime/hooks.js
index 51cc514..b524932 100644
--- a/src/runtime/hooks.js
+++ b/src/runtime/hooks.js
@@ -1,6 +1,7 @@
 import { h, options, createContext, cloneElement } from 'preact';
 import { useRef, useMemo } from 'preact/hooks';
 import { rawStore as store } from './store';
+import { scripts } from './router';
 
 // Main context.
 const context = createContext({});
@@ -143,5 +144,16 @@ options.vnode = (vnode) => {
 		vnode.type = Directive;
 	}
 
+	// if the vnode is a script
+	if (vnode.type === 'script') {
+		// if the script has a src attribute
+		if (vnode.props.src) {
+			if (scripts.has(vnode.props.src)) {
+				// if the script has already been loaded, don't load it again
+				vnode.props.src = '';
+			}
+		}
+	}
+
 	if (old) old(vnode);
 };
```

**Comment by luisherranz** [comment]
> I think that if a script has already been loaded and is in the cache, we should remove any <script> tags with a matching src.

That sounds reasonable.

> Do you have a some specific idea on how to handle it?

Not yet. I think we need to analyze this behavior better and understand all the possible implications 🙂

**Comment by luisherranz** [comment]
I'm going to close this issue as part of the migration to the Gutenberg repository.

This task was added to the Roadmap and we'll reopen an issue/discussion once it's time to start working on this again.
