### ISSUE TITLE
⚛️ Share block context between blocks

### ISSUE THREAD

**Issue by DAreRodz** [luisherranz/block-hydration-experiments#67]
Right now, blocks have two properties called `data-wp-block-provides-block-context` and `data-wp-block-uses-block-context`, containing the information of those attributes that are exposed and consumed.

The idea is to use the [Option Hooks API](https://preactjs.com/guide/v10/options/) from Preact to handle those properties as directives.

**Comment by luisherranz** [comment]
This is how I'm wrapping the vnodes that contain directives (stored in a `wp` prop in that experiment) with a component that then runs each directive.

```js
import { h, options } from "preact";

// WordPress Directives.
const directives = {};

// Expose function to add directives.
export const directive = (name, cb) => {
  directives[name] = cb;
};

const WpDirective = (props) => {
  for (const d in props.wp) {
    directives[d]?.(props);
  }
  props._wrapped = true;
  const { wp, tag, children, ...rest } = props;
  return h(tag, rest, children);
};

const old = options.vnode;

options.vnode = (vnode) => {
  const wp = vnode.props.wp;
  const wrapped = vnode.props._wrapped;

  if (wp) {
    if (!wrapped) {
      vnode.props.tag = vnode.type;
      vnode.type = WpDirective;
    }
  } else if (wrapped) {
    delete vnode.props._wrapped;
  }

  if (old) old(vnode);
};
```

https://github.com/WordPress/gutenberg/blob/9e7301b7bcf3eecf868a999e4f677c069b1f2da2/packages/block-library/src/query-pagination/directives.js

I'm not sure yet if marking the wrapped node with `_wrapped` is the best idea. Probably not, but it works for now.

**Comment by DAreRodz** [comment]
I believe this should have been closed automatically. 😕 Not sure what happened, but I had to do it myself.
