### ISSUE TITLE
⚛️ Remove the `wp-inner-blocks` wrapper

### ISSUE THREAD

**Issue by DAreRodz** [luisherranz/block-hydration-experiments#76]
We need to get rid of the `<wp-inner-blocks>` element to avoid CSS issues like https://github.com/WordPress/block-hydration-experiments/issues/50.

As @luisherranz proposed in https://github.com/WordPress/block-hydration-experiments/issues/50#issuecomment-1235334619, we can append the `wp-inner-block` attribute to those blocks that are the children of an interactive block.

```html
<div class="wp-block-parent">
  <div>Some content</div>
  <div class="wp-block-child-1" wp-inner-block>Some child content</div>
  <div class="wp-block-child-2" wp-inner-block>More child content</div>
</div>
```

Note that we need a new attribute because:
- using a regexp to find nodes with their class starting with `wp-block-"` could be not reliable enough
- using the `wp-block-type` attribute would work only if children are interactive blocks as well

**Comment by luisherranz** [comment]
Fixed in #77.
